"""Initial migration focused on validation of user related models

Revision ID: 4820ddca40b6
Revises: 
Create Date: 2024-06-06 13:25:45.541376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4820ddca40b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_email', ['email'], unique=False)
        batch_op.create_index('ix_username', ['username'], unique=False)

    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.create_index('ix_relationship_type', ['relationship_type'], unique=False)
        batch_op.create_index('ix_user_related_user', ['user_id', 'related_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_index('ix_user_related_user')
        batch_op.drop_index('ix_relationship_type')

    op.drop_table('relationship')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_username')
        batch_op.drop_index('ix_email')

    op.drop_table('user')
    # ### end Alembic commands ###
